config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comment_counter_post

  def author=(user)
    self.user_id = user.id
  end

  def update_comment_counter_post
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_like_counter_post

  def update_like_counter_post
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  after_save :update_posts_counter_user
  after_initialize :set_counters_to_zero

  def set_counters_to_zero
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end

  def update_posts_counter_user
    author.update(post_counter: author.posts.count)
  end

  def five_recent_comments_post
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id', class_name: 'Post'
  has_many :comments, foreign_key: 'user_id', class_name: 'Comment'
  has_many :likes, foreign_key: 'user_id', class_name: 'Like'

  after_initialize :set_post_counter_zero

  def set_post_counter_zero
    self.post_counter ||= 0
  end

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_parameters)
    @comment.user_id = @user.id
    @comment.post_id = @post.id

    if @comment.save
      flash[:notice] = 'The post is successfully submitted'
      redirect_to user_post_path(@user, @post)
    else
      flash[:alert] = 'Can not save the comment'
      render :new
    end
  end

  private

  def comment_parameters
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @like = Like.new(user_id: @user.id, post_id: @post.id)

    if @like.save
      flash[:notice] = 'The like is successfully submitted'
      redirect_to user_post_path(@user, @post)
    else
      flash[:alert] = 'Can not save the like'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @user = current_user
    @post = Post.new(post_parameters)
    @post.author_id = @user.id

    if @post.save
      flash[:notice] = 'The post is successfully submitted'
      redirect_to user_post_path(@user, @post)
    else
      flash[:alert] = 'Can not save the post'
      render :new
    end
  end

  private

  def post_parameters
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>This is comments #new page</h1>

<%= form_for :comment, url: user_post_comments_path(@user, @post) do |form|%>
    <div>
        <%= form.label :text %>
        <%= form.text_area :text %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="flash-msg">
    <% flash.each do |name,message| %>
      <%= message %>
    <%end%>
  </div>
  <%= yield %>
  </body>
</html>

app/views/layouts/posts/_post.html.erb
<div class="user-post">
    <a href="<%= user_post_path(@user,post) %>" class="post-desc">
        <h3 class="user-post-title"><%= post.title%></h3>
    </a>
    <p class="user-post-partial"><%= post.text%></p>
    <div class="user-post-counter">Comments: <%= post.comments_counter %>, Like: <%= post.likes_counter %></div>
</div>

app/views/layouts/users/_user.html.erb
<li class="user-item">
    <a class="img-link" href="<%=user_path(user)%>">
        <img src="<%=user.photo%>" alt="user photo">
        <div class="user-info-container">
            <h1 class="user-name"><%=user.name%></h1>
            <h4 class="user-post-num">Number of posts: <%=user.post_counter%></h4>
        </div>
    </a>
</li>

app/views/likes/new.html.erb
<h1>This is posts#new page</h1>

<%= form_for :like, url: user_post_likes_path(@user, @post) do |form|%>
    <div>
        <%= form.submit %>
    </div>
<%end%>

app/views/posts/_post.html.erb
<div class="user-post">
    <a href="<%= user_post_path(@user,post) %>" class="post-desc">
        <h3 class="user-post-title"><%= post.title%></h3>
    </a>
    <p class="user-post-partial"><%= post.text%></p>
    <div class="user-post-counter">Comments: <%= post.comments_counter %>, Like: <%= post.likes_counter %></div>
</div>

app/views/posts/index.html.erb
<h1>Show all posts for a specific user</h1>
<div class="all-post-container">
    <%= render partial: 'users/user', locals: { user: @user } %>
    <div class="posts-container">
        <% @posts.each do |post|%>
            <div class="post-comments-container">
                <%= render partial: 'posts/post', locals: { post: post } %>
                <div class="comments-container">
                    <% post.five_recent_comments_post.each do |comment| %>
                        <p class="post-comment"><%= @user.name %>: <%= comment.text %></p>
                    <%end%>
                </div>
            </div>
        <%end%>
    </div>
    <button class="see-all-post-btn">Pagination</button>
</div>

app/views/posts/new.html.erb
<h1>This is posts #new page</h1>

<%= form_for :post, url: user_posts_path(@user) do |form|%>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :text %>
        <%= form.text_field :text %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<%end%>

app/views/posts/show.html.erb
<h1>Specific post for a specific user</h1>
<div class="all-comments-container">
    <%= render partial: 'posts/post', locals: { post: @post } %>
    <div class="list-of-comments">
        <% @post.comments.each do |comment| %>
            <p class="post-comment"><%= @user.name %>: <%= comment.text %></p>
        <%end%>
    </div>
</div>

app/views/users/_user.html.erb
<li class="user-item">
    <a class="img-link" href="<%=user_path(user)%>">
        <img src="<%=user.photo%>" alt="user photo">
        <div class="user-info-container">
            <h1 class="user-name"><%=user.name%></h1>
            <h4 class="user-post-num">Number of posts: <%=user.post_counter%></h4>
        </div>
    </a>
</li>

app/views/users/index.html.erb
<h1>List of all users</h1>
<div class="users-main-container">
    <ul class="users-list-container">
        <% @users.each do |user| %> 
            <%= render partial: 'users/user', locals: { user: user } %>
        <%end%>
    </ul>
</div>

app/views/users/show.html.erb
<h1>Show a specific user</h1>
<div class="user-post-main-container">
    <%= render partial: 'users/user', locals: { user: @user } %>
    <div class="user-bio-container">
        <h4 class="user-post-bio">Bio</h4>
        <p class="user-post-bio-para"><%= @user.bio %></p>
    </div>
    <div class="list-of-posts">
        <% @user.three_recent_posts.each do |post| %>
            <%= render partial: 'posts/post', locals: { post: post } %>
        <% end %>
    </div>
    <a href="<%= user_posts_path(@user) %>">
        <button class="see-all-post-btn">See all posts</button>
    </a>
</div>